In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df=pd.read_excel('raw_smart_phone_data.xlsx')

In [3]:
df.head()

,Unnamed: 0,model_name,price,avg_rating,reviews,memory,camera,display,battary,processor,upto_exchange
0,0,"MOTOROLA g05 (Forest Green, 64 GB)","₹6,999",4.2,"49,084 Ratings & 3,352 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP Rear Camera | 8MP Front Camera,16.94 cm (6.67 inch) HD+ Display,5100 mAh Battery,Helio G81 Processor,"Upto ₹5,200 Off on Exchange"
1,1,"POCO C71 (Desert Gold, 128 GB)","₹6,999",4.1,"11,677 Ratings & 607 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,32MP Rear Camera | 8MP Front Camera,17.48 cm (6.88 inch) HD+ Display,5200 mAh Battery,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,"Upto ₹5,200 Off on Exchange"
2,2,"POCO C71 (Cool Blue, 64 GB)","₹6,399",3.9,"25,608 Ratings & 1,237 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,32MP Rear Camera | 8MP Front Camera,17.48 cm (6.88 inch) HD+ Display,5200 mAh Battery,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,"Upto ₹4,700 Off on Exchange"
3,3,"Samsung Galaxy F05 (Twilight Blue, 64 GB)","₹6,499",4.2,"64,333 Ratings & 3,625 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,17.12 cm (6.74 inch) HD+ Display,5000 mAh Battery,Helio G85 Processor,"Upto ₹4,800 Off on Exchange"
4,4,"POCO C71 (Power Black, 128 GB)","₹6,999",4.1,"11,677 Ratings & 607 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,32MP Rear Camera | 8MP Front Camera,17.48 cm (6.88 inch) HD+ Display,5200 mAh Battery,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,Super Deals

In [4]:
df.drop(['Unnamed: 0','upto_exchange'],axis=1,inplace=True)

In [5]:
df.shape

(984, 9)

In [6]:
df['battary'].duplicated().sum()

np.int64(914)

In [7]:
df['brand'] = df['model_name'].str.split().str[0]

In [8]:
df['model'] = df['model_name'].str.replace(r'\(.*?\)', '', regex=True)

In [9]:
df['color'] = df['model_name'].str.extract(r'\(([^,]+),')

In [10]:


def clean_model_name(text):
    text = text.strip()

    # stop words ONLY for extra details (colors, charger, storage, etc.)
    stop_words = [
        "with", "and", "charger", "supervooc", "mah", "battery",
        "edition", "pulse", "green", "blue", "red", "black", "white",
        "camera", "storage", "locked", "sim", "power",
        "ram", "rom", "charger", "box","only", "on", "Jio","Typse","C","Charging","4000","6000mAh","HD"
    ]

    # stop at appearance of any extra descriptive word
    pattern = r"\b(" + "|".join(stop_words) + r")\b.*$"

    cleaned = re.sub(pattern, "", text, flags=re.IGNORECASE).strip()

    # remove trailing symbols like + -
    cleaned = re.sub(r"[\+\-]+$", "", cleaned).strip()

    return cleaned

In [11]:
df['model']=df['model'].apply(clean_model_name)

In [12]:
df.head()

,model_name,price,avg_rating,reviews,memory,camera,display,battary,processor,brand,model,color
0,"MOTOROLA g05 (Forest Green, 64 GB)","₹6,999",4.2,"49,084 Ratings & 3,352 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP Rear Camera | 8MP Front Camera,16.94 cm (6.67 inch) HD+ Display,5100 mAh Battery,Helio G81 Processor,MOTOROLA,MOTOROLA g05,Forest Green
1,"POCO C71 (Desert Gold, 128 GB)","₹6,999",4.1,"11,677 Ratings & 607 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,32MP Rear Camera | 8MP Front Camera,17.48 cm (6.88 inch) HD+ Display,5200 mAh Battery,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,POCO,POCO C71,Desert Gold
2,"POCO C71 (Cool Blue, 64 GB)","₹6,399",3.9,"25,608 Ratings & 1,237 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,32MP Rear Camera | 8MP Front Camera,17.48 cm (6.88 inch) HD+ Display,5200 mAh Battery,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,POCO,POCO C71,Cool Blue
3,"Samsung Galaxy F05 (Twilight Blue, 64 GB)","₹6,499",4.2,"64,333 Ratings & 3,625 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,17.12 cm (6.74 inch) HD+ Display,5000 mAh Battery,Helio G85 Processor,Samsung,Samsung Galaxy F05,Twilight Blue
4,"POCO C71 (Power Black, 128 GB)","₹6,999",4.1,"11,677 Ratings & 607 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,32MP Rear Camera | 8MP Front Camera,17.48 cm (6.88 inch) HD+ Display,5200 mAh Battery,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,POCO,POCO C71,Power Black

In [13]:
df['brand']=df['brand'].str.capitalize()

In [14]:
df['model']=df['model'].str.capitalize()

In [15]:
df['color']=df['color'].str.capitalize()

In [16]:
df['model'].value_counts()

model
Redmi 14c 5g             16
Samsung galaxy f16 5g    13
Poco c71                 12
Poco m7 5g               11
Redmi note 14 5g         11
                         ..
Samsung a16 5g            1
Samsung galaxy f14 5g     1
Realme x3 superzoom       1
Samsung galaxy a26 5g     1
Realme narzo n65 5g       1
Name: count, Length: 276, dtype: int64

In [17]:
df['price'].isnull().sum()

np.int64(0)

In [18]:
df['price']=df['price'].str.replace('₹','').str.replace(',','').astype('int32')

In [19]:
df['avg_rating'].isnull().sum()

np.int64(1)

In [20]:
redmi_mean =round(df[df['brand'] == 'Redmi']['avg_rating'].mean(), 1)

In [21]:
df['avg_rating'] = df['avg_rating'].fillna(redmi_mean)

In [22]:
df['reviews'].isnull().sum()

np.int64(1)

In [23]:
df['reviews']=df['reviews'].fillna('0').str.split(' ').str[0].str.replace(',','').astype(int)

In [24]:
redmi_rew_mean =df[df['brand'] == 'Redmi']['reviews'].mean().astype(int)

In [25]:
redmi_rew_mean

np.int64(16523)

In [26]:
df.loc[df['reviews'] == 0, 'reviews'] = redmi_rew_mean

In [27]:
df['reviews'].isnull().sum()

np.int64(0)

In [28]:
df['RAM'] =df['memory'].str.extract(r'(\d+)\s*GB\s*RAM', expand=False)
df['ROM'] = df['memory'].str.extract(r'(\d+)\s*GB\s*ROM', expand=False)

In [29]:
df['RAM'].isnull().sum()

np.int64(47)

In [30]:
df[df['RAM'].isnull()]['model'].value_counts()

model
Apple iphone 16 plus       11
Apple iphone 14             8
Apple iphone 15             6
Apple iphone 16 pro max     6
Apple iphone 16e            4
Apple iphone 16             4
Apple iphone 16 pro         3
Apple iphone 15 plus        2
Apple iphone 14 plus        2
Apple iphone 13             1
Name: count, dtype: int64

In [31]:
df.loc[(df['model'].str.contains(r'13|14|15', case=False, na=False)) & df['RAM'].isna(), 'RAM'] = 6
df.loc[(df['model'].str.contains('16', case=False, na=False)) & df['RAM'].isna(), 'RAM'] = 8

In [32]:
df['RAM'].isnull().sum()

np.int64(0)

In [33]:
df['ROM'].isnull().sum()

np.int64(1)

In [34]:
df[df['ROM'].isnull()]

,model_name,price,avg_rating,reviews,memory,camera,display,battary,processor,brand,model,color,RAM,ROM
335,"LAVA YUVA STAR 2 (SPARKLING IVORY, 64 MB)",6799,2.0,4,4 GB RAM | 64 MB ROM,13MP Rear Camera,17.14 cm (6.75 inch) Display,5000 mAh Battery,1 YEAR MANUFACTURER WARANTY,Lava,Lava yuva star 2,Sparkling ivory,4,NaN

In [35]:
df['ROM']=df['ROM'].fillna(128)

In [36]:
df['camera'].value_counts().sum()

np.int64(984)

In [37]:
df['Rear Camera']=df['camera'].str.split('|').str[0].str.replace('Rear Camera','').str.strip().str.replace(r'\s+', ' ', regex=True)

In [38]:
df['Front Camera']=df['camera'].str.split('|').str[1].str.replace('Front Camera','').str.replace('Dual','').str.strip().str.replace(r'\s+', ' ', regex=True)

In [39]:
list(df['display'].value_counts().index)

['16.94 cm (6.67 inch) Display',
 '16.94 cm (6.67 inch) Full HD+ Display',
 '17.02 cm (6.7 inch) Full HD+ Display',
 '17.2 cm (6.77 inch) Display',
 '17.48 cm (6.88 inch) HD+ Display',
 '17.02 cm (6.7 inch) Display',
 '16.94 cm (6.67 inch) HD+ Display',
 '17.35 cm (6.83 inch) Display',
 '17.22 cm (6.78 inch) Display',
 '17.02 cm (6.7 inch) HD+ Display',
 '17.22 cm (6.78 inch) Full HD+ Display',
 '15.49 cm (6.1 inch) Super Retina XDR Display',
 '17.12 cm (6.74 inch) Display',
 '16.51 cm (6.5 inch) HD+ Display',
 '17.04 cm (6.71 inch) HD+ Display',
 '17.13 cm (6.745 inch) HD+ Display',
 '16.51 cm (6.5 inch) Full HD+ Display',
 '17.27 cm (6.8 inch) Display',
 '17.25 cm (6.79 inch) Full HD+ Display',
 '16.76 cm (6.6 inch) HD+ Display',
 '17.02 cm (6.7 inch) Super Retina XDR Display',
 '16.91 cm (6.657 inch) Full HD+ Display',
 '17.12 cm (6.74 inch) HD+ Display',
 '16.76 cm (6.6 inch) Display',
 '15.75 cm (6.2 inch) Full HD+ Display',
 '43.66 cm (17.19 cm) Full HD+ Display',
 '16.76 cm (6.6 inch) Full HD+ Display',
 '17.07 cm (6.72 inch) Display',
 '17.27 cm (6.8 inch) Quad HD+ Display',
 '16.94 cm (6.67 inch) HD Display',
 '17.22 cm (6.78 inch) Full HD+ E3 Super AMOLED Display',
 '16.94 cm (6.67 inch) Full HD+ AMOLED Display',
 '15.49 cm (6.1 inch) Full HD+ Display',
 '16.66 cm (6.56 inch) Display',
 '16.74 cm (6.59 inch) Display',
 '16.64 cm (6.55 inch) Full HD+ Display',
 '16.03 cm (6.31 inch) Display',
 '16.64 cm (6.55 inch) HD+ Display',
 '17.53 cm (6.9 inch) Super Retina XDR Display',
 '17.22 cm (6.78 inch) Full HD+ AMOLED Display',
 '17.07 cm (6.72 inch) Full HD+ Display',
 '17.2 cm (6.77 inch) Full HD+ Display',
 '16.64 cm (6.55 inch) Display',
 '17.27 cm (6.8 inch) Full HD+ Display',
 '17.22 cm (6.78 inch) HD+ Display',
 '17.48 cm (6.88 inch) Display',
 '16.0 cm (6.3 inch) Display',
 '17.14 cm (6.75 inch) HD+ Display',
 '17.2 cm (6.77 inch) Full HD+ AMOLED Display',
 '17.53 cm (6.9 inch) Quad HD+ Display',
 '17.14 cm (6.75 inch) Display',
 '17.35 cm (6.83 inch) Full HD+ Display',
 '16.0 cm (6.3 inch) Super Retina XDR Display',
 '12.7 cm (5 inch) HD Display',
 '15.96 cm (6.285 inch) Full HD+ Display',
 '16.05 cm (6.32 inch) Display',
 '17.02 cm (6.7 inch) Full HD+ AMOLED Display',
 '17.02 cm (6.7 inch) Full HD+ Super AMOLED Display',
 '17.35 cm (6.83 inch) Full HD+ AMOLED Display',
 '16.56 cm (6.52 inch) HD+ Display',
 '17.02 cm (6.7 inch) Super HD Display',
 '17.12 cm (6.74 inch) HD Display',
 '19.3 cm (7.6 inch) QXGA+ Display',
 '16.71 cm (6.58 inch) Full HD+ Display',
 '16.26 cm (6.4 inch) HD Display',
 '16.21 cm (6.38 inch) Full HD+ Display',
 '16.59 cm (6.53 inch) Full HD+ Display',
 '13.97 cm (5.5 inch) Full HD Display',
 '16.66 cm (6.56 inch) Full HD+ Display',
 '16.94 cm (6.67 inch) Full HD+ Super AMOLED Display',
 '17.25 cm (6.79 inch) Display',
 '17.02 cm (6.7 inch) Quad HD+ Display',
 '16.26 cm (6.4 inch) Super HD Display',
 '16.87 cm (6.64 inch) Full HD+ Display',
 '7.62 cm (3 inch) Display',
 '13.84 cm (5.45 inch) HD+ Display',
 '12.7 cm (5 inch) FWVGA Display',
 '16.51 cm (6.5 inch) Display',
 '17.32 cm (6.82 inch) HD+ Display',
 '15.49 cm (6.1 inch) HD+ Display',
 '15.75 cm (6.2 inch) Display',
 '16.66 cm (6.56 inch) HD Display',
 '15.77 cm (6.21 inch) HD+ Display',
 '16.36 cm (6.44 inch) Full HD+ Display',
 '17.53 cm (6.9 inch) Full HD+ Display',
 '12.7 cm (5 inch) FWVGA+ Display',
 '13.97 cm (5.5 inch) Full HD+ Display',
 '17.53 cm (6.9 inch) Display',
 '16.0 cm (6.3 inch) Full HD+ Display',
 '16.94 cm (6.67 inch) Full HD Display',
 '16.97 cm (6.68 inch) Display',
 '16.69 cm (6.57 inch) Full HD+ Display']

In [40]:
df['display_inches'] = (
    df['display']
    .str.extract(r'\(([\d\.]+)\s*inch\)', expand=False)
    .astype(float)
)

In [41]:
mask=df['display_inches'].isnull()

In [42]:
df.loc[mask,'display_inches']=round(df.loc[mask,'display'].str.extract(r'\(([\d\.]+)\s*cm\)', expand=False).astype(float)/2.54,2)

In [43]:
df[df['display_inches'].isnull()]

Empty DataFrame
Columns: [model_name, price, avg_rating, reviews, memory, camera, display, battary, processor, brand, model, color, RAM, ROM, Rear Camera, Front Camera, display_inches]
Index: []

In [44]:
df['display_type'] = (df['display'].str.extract(r'\)\s*(.+)$', expand=False))

In [45]:
# list(df['battary'].value_counts().index)

In [46]:
df['battery']=df['battary'].str.extract(r'(\d+)\s*mAh', expand=False)

In [47]:
mask=df['battery'].isnull()
df.loc[mask, ['battary','processor']]=df.loc[mask, ['battary','processor']].shift(1, axis=1)

In [48]:
 # list(df[df['battery'].isnull()]['model'])

In [49]:
df['battery']=df['battery'].fillna(4000)

In [50]:
df['battery']=df['battery'].astype('int')

In [51]:
df['processor']=df[df['processor'].str.contains('Processor')]['processor']

In [52]:
df['processor'].value_counts().sum()

np.int64(830)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   model_name      984 non-null    object
 1   price           984 non-null    int32
 2   avg_rating      984 non-null    float64
 3   reviews         984 non-null    int64
 4   memory          984 non-null    object
 5   camera          984 non-null    object
 6   display         984 non-null    object
 7   battary         937 non-null    object
 8   processor       830 non-null    object
 9   brand           984 non-null    object
 10  model           984 non-null    object
 11  color           984 non-null    object
 12  RAM             984 non-null    object
 13  ROM             984 non-null    object
 14  Rear Camera     984 non-null    object
 15  Front Camera    820 non-null    object
 16  display_inches  984 non-null    float64
 17  display_type    984 non-null    object
 18  battery         984 non-null    int64
dtypes: float64(2), int32(1), int64(2), object(14)
memory usage: 142.3+ KB

In [54]:
df=df[['brand','model','price','avg_rating','reviews','color','RAM','ROM','battery','Rear Camera','Front Camera','display_inches','display_type','processor']]

In [55]:
df.sample(5)

,brand,model,price,avg_rating,reviews,color,RAM,ROM,battery,Rear Camera,Front Camera,display_inches,display_type,processor
483,Realme,Realme c75 5g,13999,4.4,1108,Midnight lily,6,128,6000,32MP,8MP,6.670,HD+ Display,Dimensity 6300 Processor
271,Google,Google pixel 9a,49999,4.4,1977,Iris,8,256,5100,48MP + 12MP,12MP,6.285,Full HD+ Display,Tensor G4 Processor
3,Samsung,Samsung galaxy f05,6499,4.2,64333,Twilight blue,4,64,5000,50MP + 2MP,8MP,6.740,HD+ Display,Helio G85 Processor
872,Samsung,Samsung galaxy a04,12999,3.9,228,Green,4,128,5000,50MP + 2MP,5MP,6.500,HD+ Display,Mediatek Helio P35 Processor
369,Infinix,Infinix hot 10s,10999,4.3,43529,Heart of ocean,6,64,6000,48MP + 2MP + AI Lens Camera,8MP,6.820,HD+ Display,MediaTek Helio G85 Processor

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   brand           984 non-null    object
 1   model           984 non-null    object
 2   price           984 non-null    int32
 3   avg_rating      984 non-null    float64
 4   reviews         984 non-null    int64
 5   color           984 non-null    object
 6   RAM             984 non-null    object
 7   ROM             984 non-null    object
 8   battery         984 non-null    int64
 9   Rear Camera     984 non-null    object
 10  Front Camera    820 non-null    object
 11  display_inches  984 non-null    float64
 12  display_type    984 non-null    object
 13  processor       830 non-null    object
dtypes: float64(2), int32(1), int64(2), object(9)
memory usage: 103.9+ KB

In [57]:
df.describe()

               price  avg_rating        reviews      battery  display_inches
count     984.000000  984.000000     984.000000   984.000000      984.000000
mean    24813.410569    4.319614   24970.716463  5319.715447        6.660153
std     23171.502087    0.206387   52858.322342   755.287230        0.247031
min      4499.000000    2.000000       4.000000  2000.000000        3.000000
25%     10999.000000    4.200000    1112.000000  5000.000000        6.670000
50%     17414.000000    4.300000    4716.000000  5060.000000        6.700000
75%     27999.000000    4.400000   19312.000000  6000.000000        6.770000
max    157900.000000    4.700000  364334.000000  7550.000000        7.600000

In [58]:
df.duplicated().sum()

np.int64(65)

In [59]:
df = df.drop_duplicates()

In [60]:
df.to_csv('cleaned_smartphone_dataset.csv',index=False)